include: package:flutter_lints/flutter.yaml

linter:
    rules:
        # Always await, intentionally not await
        unawaited_futures: true
        prefer_single_quotes: true
        invalid_dependency: false
